# .github/workflows/build.yml

name: Build wsock32 DLL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build DLL
        run: |
          cl /LD dllmain.cpp proxy.cpp exports.cpp /link /DEF:wsock32.def /OUT:wsock32.dll

      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: wsock32
          path: wsock32.dll
